version: 2
sources:
  - name: epl_data
    database: OPTA_DATA_FOOTBALL__SAMPLE
    schema: EPL
    tables:
      - name: GAME 
      - name: PLAYER 
      - name: TEAM 
      - name: PLAYER_GAME_STATISTIC 
      - name: TEAM_GAME_STATISTIC 